/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CharactersIndexImport } from './routes/characters/index'
import { Route as CharactersIdImport } from './routes/characters/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CharactersIndexRoute = CharactersIndexImport.update({
  path: '/characters/',
  getParentRoute: () => rootRoute,
} as any)

const CharactersIdRoute = CharactersIdImport.update({
  path: '/characters/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/characters/$id': {
      preLoaderRoute: typeof CharactersIdImport
      parentRoute: typeof rootRoute
    }
    '/characters/': {
      preLoaderRoute: typeof CharactersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CharactersIdRoute,
  CharactersIndexRoute,
])

/* prettier-ignore-end */
